SELECT c.BUSINESS_NAME, SUM(s.SALES_VALUE) as TOTAL_SALES_VALUE
FROM data_store_cad c JOIN data_store_sales s
ON c.STORE_CODE = s.STORE_CODE 
WHERE s.DATE BETWEEN '2019-01-01' AND '2019-03-31'
GROUP BY c.BUSINESS_NAME 
ORDER BY TOTAL_SALES_VALUE DESC;